name: Flutter CI / Pruebas Automaticas

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.35.7'

jobs:
  static_analysis_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Preparar CLI
        run: |
          flutter --version
          flutter config --no-analytics --no-cli-animations

      - name: Instalar dependencias
        run: flutter pub get

      - name: Ejecutar análisis estático
        run: flutter analyze

      - name: Ejecutar pruebas unitarias y de widget (no golden)
        run: |
          flutter test test/widget_test.dart
          flutter test test/calc_test.dart

  golden_tests:
    runs-on: ubuntu-latest
    needs: static_analysis_and_unit_tests
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Preparar CLI
        run: |
          flutter --version
          flutter config --no-analytics --no-cli-animations

      - name: Instalar dependencias
        run: flutter pub get

      - name: Ejecutar Golden Tests (actualiza baselines)
        run: xvfb-run -a flutter test test/golden_test.dart --tags golden --update-goldens

      - name: Subir goldens como artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-images
          path: |
            **/goldens/**
            **/golden/**
            **/failures/**
          if-no-files-found: warn

  integration_tests:
    runs-on: macos-latest
    needs: static_analysis_and_unit_tests
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Preparar CLI (habilitar Web)
        run: |
          flutter --version
          flutter config --no-analytics --no-cli-animations
          flutter config --enable-web
          flutter doctor -v
          flutter devices

      - name: Instalar dependencias
        run: flutter pub get

      - name: Ejecutar pruebas de integración en Chrome
        run: flutter test -d chrome integration_test/
